//go:build amd64 && amd64.v2

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package base

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(Wasi_snapshot_preview1Imports)(nil).Clock_time_get64(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_get64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_sizes_get64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_close64(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_get64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_set_flags64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_dir_name64(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_get64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_read64(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_readdir64(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_seek64(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_write64(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_filestat_get64(nil, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_open64(nil, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_exit64(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Random_get64(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sched_yield64(nil)
	(WasmifyImports)(nil).Callback_invoke(nil, 0, 0, 0, 0)
}
